### ISSUE TITLE
運営からのお知らせが見づらいのでレイアウトを直したい

### ISSUE THREAD

**Issue by inductor** [cloudnativedaysjp/dreamkast#938]
白枠の部分の余白が全く無いのでmarginでレイアウト調整したい

4Kモニタの場合

![image](https://user-images.githubusercontent.com/20236173/137706797-eaff7b63-cd12-4ae4-865f-3d143b0af416.png)

フルHDの場合

![image](https://user-images.githubusercontent.com/20236173/137706868-46e1fb77-4793-41b6-b121-aa8eb7c3cbd2.png)

↓の`margin-top`を追加したら多少良くなった気がする

```css
.tracks {
    background-color: rgba($color: #FFF, $alpha: 1);
    margin-top: auto;
}
```

![image](https://user-images.githubusercontent.com/20236173/137707215-b64c51e0-e9e9-4901-a343-9b0ab9829e11.png)

![image](https://user-images.githubusercontent.com/20236173/137707123-95a905fc-d93a-47d9-a561-5f6212505154.png)
